import java.util.ArrayList;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
 * and D = |Pk − Pj| is minimised; what is the value of D?
 */

public class ProblemXLIV {
    public static void main(String[] args) {
        final double startTime = System.nanoTime();                                 //Starts recording runtime
        ArrayList<Integer> pentagonalList = new ArrayList<>();
        int i = 1000;
        int pentagonal1;
        boolean found = false;
        while (!found) {
            i++;
            pentagonal1 = ((3 * i * i) - i) / 2;
            for (int pentagonal2: pentagonalList) {
                if ((pentagonalList.contains(pentagonal1 - pentagonal2)) && (pentagonalList.contains(pentagonal1 - 2 * pentagonal2))) {
                    System.out.println(pentagonal1 - 2 * pentagonal2);
                    found = true;
                }
            }
            pentagonalList.add(pentagonal1);
        }
        final double duration = (System.nanoTime() - startTime) / 1000000000;       //Calculates runtime in seconds
        System.out.println("found in " + duration + " seconds");                    //Outputs runtime
    }
}
